"""One reviewed source for concise help attached to ProjectMapper controls."""

TOOLTIPS = {
    "main.project_root": "Enter the project folder to map. Press Return to open it.",
    "main.choose_root": "Choose a project folder from the file browser.",
    "main.settings": "Set adapter result limits and approval preferences.",
    "main.parent": "Move the project view up to its parent folder.",
    "main.tree": "Select files for capture. Right-click a row for file and folder tools.",
    "main.compile": "Scan selected files and build the SQLite snapshot.",
    "main.export_tree": "Export the folder and file tree as Markdown.",
    "main.export_filedump": "Export selected file contents as Markdown.",
    "main.export_combined": "Export the tree and selected file contents together.",
    "main.output_folder": "Open the folder where snapshots and exports are written.",
    "main.vendor_export": "Export the source checkout as a portable vendor package.",
    "main.diagnostics": "Check the environment and project write access.",
    "main.backups": "Review backups and undo recorded changesets.",
    "main.history": "Review recent operations, their results and affected paths.",
    "main.apply_exclusions": "When checked, matching paths are hidden from the mapper.",
    "main.tree_export": "Include the project tree in the filedump export.",
    "main.binary_blobs": "Keep selected binary file contents in the SQLite snapshot.",
    "main.select_all": "Select every visible project path for capture.",
    "main.select_none": "Clear capture selection for every project path.",
    "main.exclusion_pattern": "Enter a filename pattern to hide, such as *.log.",
    "main.add_exclusion": "Add the pattern to the exclusion rules.",
    "main.manage_exclusions": "Review, toggle and batch-manage exclusion rules.",
    "main.rescan": "Refresh the project tree and reload .gitignore rules.",
    "progress.cancel": "Request cancellation of the current operation.",
    "exclusions.apply": "Turn exclusion matching on or off for this session.",
    "exclusions.pattern": "Add a filename pattern using wildcards such as *.log.",
    "exclusions.add": "Add the entered pattern to the custom exclusion rules.",
    "exclusions.rule": "Toggle whether this rule hides matching paths. The source is shown beside it.",
    "exclusions.row_select": "Select this rule for a batch action without changing whether it is enabled.",
    "exclusions.select_all": "Select every rule for a batch action; this does not toggle rules.",
    "exclusions.deselect_all": "Clear the batch selection without changing rule states.",
    "exclusions.exclude_selected": "Turn on every selected exclusion rule.",
    "exclusions.allow_selected": "Turn off every selected exclusion rule.",
    "exclusions.delete_selected": "Remove the selected custom rules from this session.",
    "editor.open": "Open a text file in the editor.",
    "editor.save": "Save the current text after checking the source fingerprint.",
    "editor.save_as": "Save the text to another path or as a versioned copy.",
    "editor.find_replace": "Find text or replace every matching occurrence.",
    "editor.patcher": "Open the Tokenizing Patcher for this file.",
    "editor.read_only": "Prevent edits in this editor until unchecked.",
    "editor.keep_backup": "Keep a managed backup before overwriting a file.",
    "editor.text": "Edit the file contents. Save checks that the file has not changed elsewhere.",
    "editor.find": "Text to find in the current editor buffer.",
    "editor.replace": "Replacement text used by Replace All.",
    "editor.find_next": "Select the next matching text in the editor.",
    "editor.replace_all": "Replace every matching occurrence in the editor buffer.",
    "new_file.choose_folder": "Choose the folder that will contain the new file.",
    "new_file.name": "Enter the new file name without its extension.",
    "new_file.extension": "Choose the file extension to append.",
    "new_file.timestamp": "Append the current date and time to the file name.",
    "new_file.content": "Optional text to place in the new file.",
    "new_file.create": "Create the file. Existing files are never overwritten.",
    "patcher.reload": "Reload the source file and discard the current review state.",
    "patcher.load": "Load a patch proposal from a JSON file.",
    "patcher.schema": "Copy the single-file patch example to the clipboard.",
    "patcher.indent": "Allow patch indentation to be adjusted to the target context.",
    "patcher.validate": "Check the patch against the original file and show a preview.",
    "patcher.link": "Link the actions so one click validates and applies to the result pane.",
    "patcher.apply": "Apply the validated patch to the result pane; the file is not changed yet.",
    "patcher.save": "Write the reviewed result to the project file.",
    "patcher.version": "Save the result as a new version instead of overwriting the source.",
    "patcher.backup": "Keep a managed backup when saving over an existing file.",
    "patcher.suffix": "Suffix added to the file name when saving a new version.",
    "patcher.proposal": "Edit or review the JSON patch proposal for this file.",
    "project_patcher.schema": "Copy the version 2 project-transform example to the clipboard.",
    "project_patcher.load": "Load a version 1 patch or version 2 project changeset from JSON.",
    "project_patcher.add_file": "Add a file patch operation to the project proposal.",
    "project_patcher.indent": "Allow patch indentation to be adjusted to target context.",
    "project_patcher.validate": "Validate the complete proposal and show its operation review.",
    "project_patcher.link": "Link the actions so one click validates and applies the proposal.",
    "project_patcher.apply": "Apply the reviewed operations as one undoable changeset.",
    "project_patcher.backup": "Keep a separate content backup before applying the changeset.",
    "project_patcher.proposal": "Edit or review the JSON project patch or changeset proposal.",
    "project_patcher.list": "Choose an operation to inspect its source, diff and result.",
    "project_patcher.prev_operation": "Move to the previous reviewed operation. (Alt+Up)",
    "project_patcher.next_operation": "Move to the next reviewed operation. (Alt+Down)",
    "project_patcher.prev_hunk": "Move to the previous changed hunk. (Shift+F8)",
    "project_patcher.next_hunk": "Move to the next changed hunk. (F8)",
    "backups.refresh": "Reload available backup generations. (F5)",
    "backups.delete": "Delete the selected verified backup generation after approval.",
    "backups.cleanup": "Preview and remove older backup generations after approval.",
    "backups.keep": "Keep this many newest eligible generations during clean-up.",
    "backups.scope": "Choose whether clean-up applies to project or user backups.",
    "backups.generations": "Select a generation to inspect, restore or undo.",
    "backups.files": "Select a file to compare its current and saved contents.",
    "backups.restore_file": "Restore the selected file after reviewing the preview.",
    "backups.restore_all": "Restore all selected generation contents, or undo its changeset.",
    "history.category": "Show operations from one action category.",
    "history.outcome": "Filter operations by their current or final status.",
    "history.contains": "Show operations whose action, path or error contains this text.",
    "history.clear": "Clear the filter fields and show recent operations again.",
    "history.refresh": "Refresh the operation list. (F5)",
    "history.operations": "Select an operation to view its details and affected paths.",
    "history.backups": "Open Backups to inspect or undo a recorded change.",
    "settings.result_limit": "Maximum JSON result size returned to an agent, in KiB.",
    "settings.resource_limit": "Maximum snapshot resource size returned to an agent, in KiB.",
    "settings.approval_timeout": "Seconds before an unanswered approval request is denied.",
    "settings.single_approval": "Ask before each guarded single-file write from an adapter.",
    "settings.structural_approval": "Also ask before safe creates, folder creation and moves.",
    "settings.cancel": "Close Settings without saving changes.",
    "settings.save": "Save these settings for adapter processes started later.",
    "approval.approve": "Approve this reviewed operation plan.",
    "approval.deny": "Deny this plan. Nothing in it will be written.",
}
